package units.autogenerated;

import units.factory.Unit;
import weapons.*;

public class 4.2462585627515175 extends Unit { 

public 4.2462585627515175() {

    this.setJob("4.2462585627515175");
    this.addWeapon(new Fire());
    this.setHpBase(21);
    this.setCurrentHp(this.getHpBase());
    this.setStrBase(4);
    this.setSkillBase(8);
    this.setSpeedBase(6);
    this.setLuckBase(4);
    this.setDefBase(7);
    this.setResBase(4);

    this.setHpGr(80);
    this.setStrGr(35);
    this.setSkillGr(45);
    this.setSpeedGr(45);
    this.setLuckGr(20);
    this.setDefGr(50);
    this.setResGr(25);

    this.setStrCap(23);
    this.setSkillCap(27);
    this.setSpeedCap(28);
    this.setDefCap(27);
    this.setResCap(21);
    }
}
