package units.autogenerated;

import units.factory.Unit;
import weapons.*;

public class 4.282206924458522 extends Unit { 

public 4.282206924458522() {

    this.setJob("4.282206924458522");
    this.addWeapon(new IronAxe());
    this.setHpBase(22);
    this.setCurrentHp(this.getHpBase());
    this.setStrBase(5);
    this.setSkillBase(7);
    this.setSpeedBase(7);
    this.setLuckBase(7);
    this.setDefBase(5);
    this.setResBase(2);

    this.setHpGr(50);
    this.setStrGr(50);
    this.setSkillGr(50);
    this.setSpeedGr(45);
    this.setLuckGr(60);
    this.setDefGr(25);
    this.setResGr(20);

    this.setStrCap(23);
    this.setSkillCap(27);
    this.setSpeedCap(28);
    this.setDefCap(24);
    this.setResCap(24);
    }
}
