package units.autogenerated;

import units.factory.Unit;
import weapons.*;

public class 4.545100753852809 extends Unit { 

public 4.545100753852809() {

    this.setJob("4.545100753852809");
    this.addWeapon(new IronAxe());
    this.setHpBase(23);
    this.setCurrentHp(this.getHpBase());
    this.setStrBase(8);
    this.setSkillBase(8);
    this.setSpeedBase(6);
    this.setLuckBase(4);
    this.setDefBase(4);
    this.setResBase(3);

    this.setHpGr(55);
    this.setStrGr(60);
    this.setSkillGr(40);
    this.setSpeedGr(55);
    this.setLuckGr(25);
    this.setDefGr(40);
    this.setResGr(15);

    this.setStrCap(30);
    this.setSkillCap(24);
    this.setSpeedCap(25);
    this.setDefCap(23);
    this.setResCap(23);
    }
}
