package units.autogenerated;

import units.factory.Unit;
import weapons.*;

public class 4.640895757052848 extends Unit { 

public 4.640895757052848() {

    this.setJob("4.640895757052848");
    this.addWeapon(new IronSword());
    this.setHpBase(22);
    this.setCurrentHp(this.getHpBase());
    this.setStrBase(8);
    this.setSkillBase(4);
    this.setSpeedBase(8);
    this.setLuckBase(6);
    this.setDefBase(6);
    this.setResBase(1);

    this.setHpGr(50);
    this.setStrGr(55);
    this.setSkillGr(45);
    this.setSpeedGr(45);
    this.setLuckGr(25);
    this.setDefGr(40);
    this.setResGr(35);

    this.setStrCap(24);
    this.setSkillCap(27);
    this.setSpeedCap(26);
    this.setDefCap(25);
    this.setResCap(21);
    }
}
