package units.autogenerated;

import units.factory.Unit;
import weapons.*;

public class Ballistician extends Unit { 

public Ballistician() {

    this.setJob("Ballistician");
    this.addWeapon(new IronBow());
    this.setHpBase(22);
    this.setCurrentHp(this.getHpBase());
    this.setStrBase(6);
    this.setSkillBase(7);
    this.setSpeedBase(9);
    this.setLuckBase(2);
    this.setDefBase(7);
    this.setResBase(2);

    this.setHpGr(70);
    this.setStrGr(50);
    this.setSkillGr(60);
    this.setSpeedGr(25);
    this.setLuckGr(40);
    this.setDefGr(25);
    this.setResGr(20);

    this.setStrCap(26);
    this.setSkillCap(26);
    this.setSpeedCap(28);
    this.setDefCap(27);
    this.setResCap(22);
    }
}
