package units.autogenerated;

import units.factory.Unit;
import weapons.*;

public class Marauder extends Unit {

	public Marauder(){
		this.setJob("Marauder");
		this.addWeapon(new IronAxe());
		this.addWeapon(new Fire());
		this.setHpBase(23);
		this.setCurrentHp(this.getHpBase());
		this.setStrBase(6);
		this.setSkillBase(6);
		this.setSpeedBase(6);
		this.setLuckBase(7);
		this.setDefBase(7);
		this.setResBase(1);

		this.setHpGr(80);
		this.setStrGr(40);
		this.setSkillGr(35);
		this.setSpeedGr(40);
		this.setLuckGr(30);
		this.setDefGr(45);
		this.setResGr(20);

		this.setStrCap(27);
		this.setSkillCap(27);
		this.setSpeedCap(26);
		this.setDefCap(26);
		this.setResCap(22);
	}
}
