package units.autogenerated;

import units.factory.Unit;
import weapons.*;

public class Viking extends Unit {

	public Viking() {

		this.setJob("Viking");
		this.addWeapon(new IronAxe());
		this.addWeapon(new Fire());
		this.setHpBase(23);
		this.setCurrentHp(this.getHpBase());
		this.setStrBase(7);
		this.setSkillBase(5);
		this.setSpeedBase(6);
		this.setLuckBase(8);
		this.setDefBase(6);
		this.setResBase(1);

		this.setHpGr(90);
		this.setStrGr(35);
		this.setSkillGr(35);
		this.setSpeedGr(35);
		this.setLuckGr(30);
		this.setDefGr(45);
		this.setResGr(20);

		this.setStrCap(25);
		this.setSkillCap(25);
		this.setSpeedCap(30);
		this.setDefCap(30);
		this.setResCap(22);
	}
}
