package units.autogenerated;

import units.factory.Unit;
import weapons.*;

public class Woodcutter extends Unit { 

public Woodcutter() {

    this.setJob("Woodcutter");
    this.addWeapon(new IronAxe());
    this.addWeapon(new Lightning());
    this.setHpBase(20);
    this.setBaseCrit(15);
    this.setCurrentHp(this.getHpBase());
    this.setStrBase(5);
    this.setSkillBase(8);
    this.setSpeedBase(5);
    this.setLuckBase(6);
    this.setDefBase(5);
    this.setResBase(4);

    this.setHpGr(40);
    this.setStrGr(40);
    this.setSkillGr(55);
    this.setSpeedGr(40);
    this.setLuckGr(60);
    this.setDefGr(55);
    this.setResGr(30);

    this.setStrCap(23);
    this.setSkillCap(30);
    this.setSpeedCap(24);
    this.setDefCap(29);
    this.setResCap(21);
    }
}
