package units.factory;

import java.util.ArrayList;

import units.designed.*;
import units.autogenerated.*;

public class ClassList {

	ArrayList<Unit> releasedClasses = new ArrayList<>();

	public ClassList() {
		releasedClasses.add(new Assassin());
		releasedClasses.add(new Bael());
		releasedClasses.add(new Berserker());
		releasedClasses.add(new Bishop());
		releasedClasses.add(new Chosen());
		releasedClasses.add(new Crusader());
		releasedClasses.add(new DarkKnight());
		releasedClasses.add(new Druid());
		releasedClasses.add(new Fencer());
		releasedClasses.add(new General());
		releasedClasses.add(new Geomancer());
		releasedClasses.add(new GreatKnight());
		releasedClasses.add(new Halberdier());
		releasedClasses.add(new Hero());
		releasedClasses.add(new Journeyman());
		releasedClasses.add(new Lancer());
		releasedClasses.add(new Marauder());
		releasedClasses.add(new Mercenary());
		releasedClasses.add(new Mogall());
		releasedClasses.add(new Ninja());
		releasedClasses.add(new Nomad());
		releasedClasses.add(new Paladin());
		releasedClasses.add(new Pegasus());
		releasedClasses.add(new Pupil());
		releasedClasses.add(new Recruit());
		releasedClasses.add(new Sage());
		releasedClasses.add(new Sniper());
		releasedClasses.add(new Spellblade());
		releasedClasses.add(new Swordmaster());
		releasedClasses.add(new Tank());
		releasedClasses.add(new Templar());
		releasedClasses.add(new Valkyrie());
		releasedClasses.add(new Warrior());
		releasedClasses.add(new Woodcutter());
		releasedClasses.add(new WyvernLord());

	}

	public ArrayList<Unit> getReleasedUnits() {
		return releasedClasses;
	}
}